version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - custom
    volumes:
      - db_data:/var/lib/postgresql/data

  test_db:
    container_name: "test_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - custom
    volumes:
      - test_db_data:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    command: >
      redis-server /etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}



networks:
  custom:
    driver: bridge
volumes:
  db_data:
  redis_data:
  test_db_data:
